### ISSUE TITLE
Citation Needed (Possible test results to make use of) 

### ISSUE THREAD

**Issue by ross-spencer** [marhop/droidsfmin#4]
Hi Martin,

@richardlehane sent me a link to this repo. It's really cool! I hope to give it a try sometime. 

I notice in your README you have 'citation needed' for quicker format identification when using a restricted signature file. It may or may not help, but I've just been doing some work on the opposite - DROID being slower for certain subsets of file format because of their signatures - my suggestion as a potential workflow optimization was to restrict the signature file using a tool like this or Richard's ROY tool for Siegfried. 

Maybe check out the report, and if it's useful it may provide a useful testing reference. http://openpreservation.org/blog/2016/08/22/digital-preservation-stage-boss-one-the-performance-of-file-format-identification-tools-vs-checksum-generation-tools/ 

Cheers,

Ross

**Comment by marhop** [comment]
Hi Ross,

thanks a lot for you input and sorry the reply took so long - vacation, other work, iPRES, whatever ;-) Your report was indeed a very interesting read. I think the variable length signatures in PRONOM certainly deserve a closer look ...

Anyway, I built some benchmarking tools to compare the performance of DROID using different signature files (commit ad37d86bd1daf819deafd6813a87eaff51b1b3df - may be useful for you too?). Just have to write down the results so I can insert a blog post link or something instead of the TODO marker.

Best regards,
Martin

**Comment by marhop** [comment]
Can't believe this took me half a year, but anyway. I now wrote a [blog post about the performance gained by minimizing the DROID signature file](https://martin.hoppenheit.info/blog/2017/minimizing-the-droid-signature-file/) and referenced it in the README file.
